import React from 'react';
import { useNavigate } from 'react-router-dom';

export default function TermsPage() {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-white pb-16">
      <div className="px-5 pt-14 pb-4 flex items-center gap-3">
        <button
          onClick={() => navigate(-1)}
          className="w-9 h-9 rounded-full bg-gray-100 flex items-center justify-center"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#374151" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M15 18l-6-6 6-6" />
          </svg>
        </button>
        <h1 className="text-xl font-bold text-gray-900">Terms of Service</h1>
      </div>

      <div className="px-5 prose prose-sm max-w-none text-gray-700 space-y-6">
        <p className="text-xs text-gray-400">Last updated: July 2026</p>

        <section>
          <h2 className="text-base font-bold text-gray-900 mb-2">1. Acceptance</h2>
          <p className="text-sm">By creating an account or using Second Rise, you agree to these Terms of Service. If you do not agree, do not use the app. These terms apply to all users of the Second Rise mobile app and web application.</p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-900 mb-2">2. Not medical advice</h2>
          <p className="text-sm">Second Rise is a wellness and fitness app. It is <strong>not a medical device</strong> and does not provide medical advice, diagnosis, or treatment. Workout recommendations are generated by an AI system based on self-reported data and wearable metrics — they are not a substitute for advice from a qualified healthcare provider.</p>
          <p className="text-sm mt-2">If you have a medical condition, injury, or concern, consult a licensed physician or physical therapist before beginning any exercise program. If you experience chest pain, severe shortness of breath, or other symptoms during exercise, stop immediately and seek medical attention.</p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-900 mb-2">3. Eligibility</h2>
          <p className="text-sm">You must be at least 18 years old to use Second Rise. By creating an account, you represent that you meet this requirement.</p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-900 mb-2">4. Your account</h2>
          <p className="text-sm">You are responsible for keeping your account credentials secure. Do not share your password. Notify us immediately at secondriseapp@gmail.com if you suspect unauthorized access. We are not liable for losses resulting from unauthorized access due to your failure to keep credentials secure.</p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-900 mb-2">5. Wearable integrations</h2>
          <p className="text-sm">Connecting a wearable device (Oura, Whoop, Apple Health, Google Health, Fitbit, Garmin) grants Second Rise read access to specific health metrics via OAuth. You can revoke this access at any time in your profile settings. Second Rise is not affiliated with or endorsed by any wearable manufacturer.</p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-900 mb-2">6. Acceptable use</h2>
          <p className="text-sm">You agree not to: attempt to reverse-engineer the app, access other users' data, use the app for commercial resale, or submit false information that could harm the integrity of recommendations for others in a shared cohort.</p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-900 mb-2">7. Limitation of liability</h2>
          <p className="text-sm">To the fullest extent permitted by law, Second Rise and its operator are not liable for any injury, loss, or damage resulting from use of the app or reliance on its recommendations. The app is provided "as is" without warranties of any kind. Your use of the app is at your own risk.</p>
          <p className="text-sm mt-2">In no event shall our liability exceed the amount you paid for the service in the 12 months prior to the claim (which for free users is $0).</p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-900 mb-2">8. Service availability</h2>
          <p className="text-sm">We do our best to keep Second Rise running reliably, but we do not guarantee uninterrupted availability. We may modify, suspend, or discontinue features at any time. For cohort participants, we will provide reasonable advance notice of any service changes that affect the program.</p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-900 mb-2">9. Termination</h2>
          <p className="text-sm">You may delete your account at any time from Profile → Delete Account. We may suspend or terminate accounts that violate these terms. Upon termination, your data is permanently deleted.</p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-900 mb-2">10. Governing law</h2>
          <p className="text-sm">These terms are governed by the laws of the State of California, without regard to its conflict of law provisions. Any disputes shall be resolved in the courts of Santa Clara County, California.</p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-900 mb-2">11. Changes to these terms</h2>
          <p className="text-sm">We may update these terms. If we make material changes, we will notify you in the app. Continued use after notification constitutes acceptance of the revised terms.</p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-900 mb-2">12. Contact</h2>
          <p className="text-sm">Questions about these terms? Email <a href="mailto:secondriseapp@gmail.com" className="text-blue-500">secondriseapp@gmail.com</a>.</p>
        </section>
      </div>
    </div>
  );
}
